#
# OH MY ZSH
#

export ZSH=$HOME/.oh-my-zsh # Path to your oh-my-zsh installation.
ZSH_THEME="dstufft" # Set name of the theme to load.
DISABLE_UPDATE_PROMPT="true" # Disable auto-update prompt
export UPDATE_ZSH_DAYS=7 # How often to auto-update (in days).
COMPLETION_WAITING_DOTS="true" # Display red dots while waiting for completion.
HIST_STAMPS="yyyy-mm-dd" # Change the command execution timestamp shown in the history command output.

plugins=(
  vi-mode vim-interaction
  tmux git git-flow
  npm
  docker docker-compose docker-machine
)

source $ZSH/oh-my-zsh.sh


#
# USER CONFIGURATION
#

[ -f ~/.shrc ] && source ~/.shrc # Load general purpose shell configuration
[ -f ~/.localshrc ] && source ~/.localshrc # Load local general purpose shell configuration


#
# THIRD-PARTY CONFIGURATION
#

# Added by n-install (see http://git.io/n-install-repo).
export N_PREFIX="$HOME/Projects/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
