# PATH
export PATH="/usr/local/sbin:$PATH"

#
# OH MY ZSH
#

zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 7

export ZSH=$HOME/.oh-my-zsh # Path to your oh-my-zsh installation.
ZSH_THEME="dstufft" # Set name of the theme to load.
COMPLETION_WAITING_DOTS="true" # Display red dots while waiting for completion.
HIST_STAMPS="yyyy-mm-dd" # Change the command execution timestamp shown in the history command output.

plugins=(
  vi-mode vim-interaction
  tmux git git-flow
  dotenv
  npm
  docker docker-compose docker-machine
)

source $ZSH/oh-my-zsh.sh


#
# USER CONFIGURATION
#

[ -f ~/.shrc ] && source ~/.shrc # Load general purpose shell configuration
[ -f ~/.localshrc ] && source ~/.localshrc # Load local general purpose shell configuration


#
# THIRD-PARTY CONFIGURATION
#

# Added by n-install (see http://git.io/n-install-repo).
export N_PREFIX="$HOME/Projects/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"

# gpg
export GPG_TTY=`tty`

# npm
export PATH="./node_modules/.bin:$PATH"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# psql
export PATH="/usr/local/opt/libpq/bin:$PATH"

# ALIASES
alias vim="nvim"
